### ISSUE TITLE
Include arch target in release files

### ISSUE THREAD

**Issue by williamboman** [Galarius/opencl-language-server#1]
Hi! I'm now looking at adding this server to the neovim client :). I was wondering if you think it'd make sense to include the target architecture in the release files, for example `opencl-language-server-linux_x86_64.zip`? I think it'd help avoid some confusion for people downloading them without thinking about the compatible arch.

Also as a side-note: multi arch builds would be really cool, but they're a bit tedious to set up :D

**Comment by williamboman** [comment]
Oh also, changing the name of a release asset file from one release to another might cause some issues for tools who rely on the same release file existing across releases. If you think it makes sense adding the target arch to the `.zip` file names, I think it'd be perfectly fine to modify the `0.1` release directly (if this is possible), seeing as this project is so new.

**Comment by Galarius** [comment]
I have updated release assets to:

```
opencl-language-server-darwin-x86_64.zip
opencl-language-server-linux-x86_64.zip
opencl-language-server-win32-x86_64.zip
```

The format is `opencl-language-server-<platform>-<arch>`.

> Also as a side-note: multi arch builds would be really cool, but they're a bit tedious to set up :D

Agreed, it would be nice to add fat builds. I hope to get my hands on it some day :)

**Comment by williamboman** [comment]
Great, thanks!! Did #2 manage to make it into the new builds?

**Comment by Galarius** [comment]
> Did #2 manage to make it into the new builds?

Sorry, but I did not rebuild the server.

**Comment by Galarius** [comment]
@williamboman, I published artifacts of the fixed server in [0.2](https://github.com/Galarius/opencl-language-server/releases/tag/0.2).

**Comment by williamboman** [comment]
Thanks @Galarius!!

nvim-lsp-installer picks these releases up automatically 👇 ;)
<img width="588" alt="Screenshot 2022-01-12 at 21 58 07" src="https://user-images.githubusercontent.com/6705160/149220476-1dd5e709-394f-4738-bda9-0d6eebd46bad.png">

**Comment by Galarius** [comment]
By the way, I changed `zip` to `tar.gz` for macOS and Linux artifacts. 
@williamboman, could you update lsp-installer on your side if needed?
